version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: blns_col
        description: "The primary key for this table"

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"


  - name: aggregates
    description: "Aggregates"
    columns:
      - name: TIS
        description: "The primary key for this table"
        tests:
          - not_null